export const PRODUCTS = [
    {
        id: "pad-001",
        title: "Ceramic Brake Pads - Front",
        category: "Brakes",
        makes: ["Toyota", "Honda", "Ford"],
        models: ["Camry", "Civic", "F-150"],
        price: 79.99,
        sku: "CP-1001",
        availability: 12,
        rating: 4.6,
        images: [
            "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=60",
        ],
        specs: { material: "Ceramic", fitment: "Front Axle", warranty: "2 years" },
        reviews: [
            { id: 1, author: "Sam", text: "Stopped like new. Quiet.", stars: 5 },
            { id: 2, author: "Priya", text: "Good value for money.", stars: 4 },
        ],
        related: ["rotor-001"],
    },
    {
        id: "bat-001",
        title: "12V AGM Battery - 600 CCA",
        category: "Batteries",
        makes: ["Ford", "Chevrolet"],
        models: ["F-150", "Silverado"],
        price: 129.99,
        sku: "BAT-600AGM",
        availability: 5,
        rating: 4.3,
        images: [
            "https://images.unsplash.com/photo-1614039113510-3d4e2fe4b6f8?auto=format&fit=crop&w=800&q=60",
        ],
        specs: { voltage: "12V", cca: 600, warranty: "3 years" },
        reviews: [{ id: 3, author: "Diego", text: "Reliable start every time.", stars: 5 }],
        related: [],
    },
    {
        id: "tire-001",
        title: "All-Season Tire 205/55R16",
        category: "Tires",
        makes: ["Toyota", "Honda", "Mazda"],
        models: ["Corolla", "Civic", "Mazda3"],
        price: 89.5,
        sku: "TIRE-AS-20555R16",
        availability: 40,
        rating: 4.1,
        images: [
            "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=60",
        ],
        specs: { size: "205/55R16", type: "All-Season" },
        reviews: [{ id: 4, author: "Hana", text: "Comfortable ride.", stars: 4 }],
        related: [],
    },
    {
        id: "rotor-001",
        title: "Front Brake Rotor - OEM Fit",
        category: "Brakes",
        makes: ["Toyota"],
        models: ["Camry"],
        price: 59.99,
        sku: "ROT-2001",
        availability: 8,
        rating: 4.4,
        images: [
            "https://images.unsplash.com/photo-1519397151401-3f2f4b9eda5d?auto=format&fit=crop&w=800&q=60",
        ],
        specs: { diameter: "280mm", type: "Vented" },
        reviews: [],
        related: ["pad-001"],
    },
    {
    id: "pad-001",
    title: "Ceramic Brake Pads - Front",
    category: "Brakes",
    makes: ["Toyota", "Honda", "Ford"],
    models: ["Camry", "Civic", "F-150"],
    price: 79.99,
    sku: "CP-1001",
    availability: 12,
    rating: 4.6,
    images: [
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { material: "Ceramic", fitment: "Front Axle", warranty: "2 years" },
    reviews: [
      { id: 1, author: "Sam", text: "Stopped like new. Quiet.", stars: 5 },
      { id: 2, author: "Priya", text: "Good value for money.", stars: 4 },
    ],
    related: ["rotor-001"],
  },
  {
    id: "bat-001",
    title: "12V AGM Battery - 600 CCA",
    category: "Batteries",
    makes: ["Ford", "Chevrolet"],
    models: ["F-150", "Silverado"],
    price: 129.99,
    sku: "BAT-600AGM",
    availability: 5,
    rating: 4.3,
    images: [
      "https://images.unsplash.com/photo-1614039113510-3d4e2fe4b6f8?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { voltage: "12V", cca: 600, warranty: "3 years" },
    reviews: [{ id: 3, author: "Diego", text: "Reliable start every time.", stars: 5 }],
    related: [],
  },
  {
    id: "rotor-001",
    title: "Front Brake Rotor - OEM Fit",
    category: "Brakes",
    makes: ["Toyota"],
    models: ["Camry"],
    price: 59.99,
    sku: "ROT-2001",
    availability: 8,
    rating: 4.4,
    images: [
      "https://images.unsplash.com/photo-1519397151401-3f2f4b9eda5d?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { diameter: "280mm", type: "Vented" },
    reviews: [],
    related: ["pad-001"],
  },
  {
    id: "oil-001",
    title: "Synthetic Engine Oil 5W-30 - 5L",
    category: "Fluids",
    makes: ["Honda", "Toyota", "Nissan"],
    models: ["Accord", "Corolla", "Altima"],
    price: 39.99,
    sku: "OIL-5W30-5L",
    availability: 25,
    rating: 4.7,
    images: [
      "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { viscosity: "5W-30", type: "Full Synthetic", volume: "5L" },
    reviews: [{ id: 5, author: "Liam", text: "Engine runs smooth.", stars: 5 }],
    related: [],
  },
  {
    id: "light-001",
    title: "LED Headlight Bulb Kit - H11",
    category: "Lighting",
    makes: ["Toyota", "Hyundai", "Ford"],
    models: ["Camry", "Elantra", "Escape"],
    price: 59.99,
    sku: "LED-H11-KIT",
    availability: 30,
    rating: 4.5,
    images: [
      "https://images.unsplash.com/photo-1607863680603-0b57fb8d33c3?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { type: "LED", brightness: "6000K", warranty: "1 year" },
    reviews: [{ id: 6, author: "Emma", text: "Much brighter than stock.", stars: 5 }],
    related: [],
  },
  {
    id: "filter-001",
    title: "Engine Air Filter",
    category: "Filters",
    makes: ["Honda", "Mazda"],
    models: ["Civic", "Mazda3"],
    price: 19.99,
    sku: "AF-2001",
    availability: 50,
    rating: 4.2,
    images: [
      "https://images.unsplash.com/photo-1609091839311-3f89cbf0c7bc?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { type: "Paper Element", fitment: "Engine Intake" },
    reviews: [{ id: 7, author: "Noah", text: "Easy to install.", stars: 4 }],
    related: [],
  },
  {
    id: "tool-001",
    title: "Mechanic Tool Set - 150 Pieces",
    category: "Tools",
    makes: [],
    models: [],
    price: 199.99,
    sku: "TOOL-SET-150",
    availability: 10,
    rating: 4.8,
    images: [
      "https://images.unsplash.com/photo-1602299620560-10b19147ee20?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { pieces: 150, case: "Hard Case Included" },
    reviews: [{ id: 8, author: "Sophia", text: "Complete set, great quality.", stars: 5 }],
    related: [],
  },
  {
    id: "alt-001",
    title: "Alternator - 120A",
    category: "Electronics",
    makes: ["Ford", "Chevrolet"],
    models: ["Focus", "Malibu"],
    price: 149.99,
    sku: "ALT-120A",
    availability: 7,
    rating: 4.3,
    images: [
      "https://images.unsplash.com/photo-1609840110531-399a097e3bc7?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { amperage: "120A", voltage: "12V" },
    reviews: [{ id: 9, author: "Ava", text: "Fixed my charging issue.", stars: 5 }],
    related: [],
  },
  {
    id: "belt-001",
    title: "Serpentine Drive Belt",
    category: "Belts",
    makes: ["Toyota", "Honda"],
    models: ["Accord", "Camry"],
    price: 34.99,
    sku: "BELT-2001",
    availability: 15,
    rating: 4.0,
    images: [
      "https://images.unsplash.com/photo-1619710288020-07a4f04b4d43?auto=format&fit=crop&w=800&q=60",
    ],
    specs: { length: "2200mm", ribs: 6, warranty: "1 year" },
    reviews: [{ id: 10, author: "Ethan", text: "Good fit and quality.", stars: 4 }],
    related: [],
  },
];

export function getProductById(id) {
    return PRODUCTS.find((p) => p.id === id) || null;
}